---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: debian-8.2
  - name: centos-7.1

suites:
  - name: default
    run_list: [
      "recipe[crystal::prepare]",
      "recipe[crystal::install]"
    ]
    attributes:
