---
driver:
  name: docker
  privileged: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1
    run_list:
      - recipe[crystal::prepare]
      - recipe[crystal::install]

